version: '3'

services:
  app:
    image: chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    ports:
      - 3002:3002
    environment:
      # 二选一
      OPENAI_API_KEY: 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
      # HTTPS 代理，可选，支持 http，https，socks5
      HTTPS_PROXY: http://127.0.0.1:33210